### PR TITLE
(fix) normalise line endings before processing subtitle data

### PR DESCRIPTION
**Pull request by noopkat**
Hi there!

Thanks for writing it this library! 😄 Parsing text files is tricky work so I appreciate being able to use this package.

I ran into a snag where my srt objects were failing to have index props added after the first index/subtitle.
Turns out trimming the previous line within the index conditional fixed this for me, and makes the checking a little more robust. See the code change for what I mean.

Tests are still passing locally.

Thanks for considering this pull request! 🙇‍♀️

### CODE REVIEW

**Comment by radiovisual** [comment]
@noopkat, Hey! Thanks for contributing! 🎉 

I am happy to merge this, the patch looks good. 

But while we are at it, can you describe (or paste here, even better: adding in a test case with the old srt sample that would break) so that I can see the exact problem this PR solves. Are you saying that it the parsing would fail if there was a line that appeared blank, but in reality had whitespace character(s) in it, so trimming the line was all that was needed?

**Comment by noopkat** [comment]
hi @radiovisual,

Thanks for such a fast response! So all of your questions were totally valid, and prompted me to go back and really think about why this might be happening. I had a hunch that it might have to do with the fact that I'm working with a subtitle file on Windows, or a file that was produced while using Windows.

Turns out that was the right path to investigate. The `\r\n` carriage return newlines that Windows uses was messing up the splitting of the lines. Normalizing the newlines ended up being a much more robust and "correct" bug fix.

As for the output, before I fixed this, it looked like this:
```javascript
[
  {
    index: '1',
    timestamp: '00:00:55,880 --> 00:00:57,670',
    start: '00:00:55,880',
    end: '00:00:57,670',
    text: 'Line one'
   }, {
    timestamp: '00:01:12,270 --> 00:01:13,390',
    start: '00:01:12,270',
    end: '00:01:13,390',
    text: '2\nLine two\nLine three\nLine four\nLine five'
  }
]
```

You'll notice that the first worked (thanks to the index 0 conditional) but after that each would prepend the index number to the beginning of the `text` property, which was the giveaway.

I have pushed up an amended fix, ~~however this introduces a dependency into a previously dependency free package (other than dev deps). Is this ok? I figure using a library for normalizing is a good idea.~~ 

**EDIT:** ~~I just looked at the normalize library I used and it would be a one line addition to your code rather than importing an entire dependency /facepalm so let me know and I'll just add a regex replace one-liner instead~~ did this instead 😅

I also added a new test to catch this, and have placed a windows formatted subtitle fixture for the test to use.

Let me know what you think! 😄

**Comment by radiovisual** [comment]
> I just looked at the normalize library I used and it would be a one line addition to your code rather than importing an entire dependency /facepalm so let me know and I'll just add a regex replace one-liner instead 

haha. yeah, on my way over to the computer (I read your message from my phone) I was thinking: "I bet the dependency she added can be replaced with a single regex", and then when I got to my computer I saw you had made this edit. 😆 

Awesome. Thanks for everything! It all looks good to me. Merged! 👍

**Comment by radiovisual** [comment]
@noopkat, published to version `0.0.3`, thanks for everything! 💃

**Comment by noopkat** [comment]
Thanks @radiovisual, it was a pleasure to work with you!

bitmoji

**Pull request merged**
